apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  minReadySeconds: 10  # Specifies the minimum number of seconds for which a newly created Pod should be ready before considering it available.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # Specifies the maximum number of Pods that can be created over the desired number of Pods during a rolling update.
      maxUnavailable: 1  # Specifies the maximum number of Pods that can be unavailable during a rolling update.
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
